server:
  port: 8083
spring:
  profiles:
    active: dev
  datasource:
    url:
      jdbc:mysql://baac3d3e572fba:32b37ff9251e59a@us-cdbr-iron-east-04.cleardb.net/heroku_b31ef5fea691291?reconnect=true&useUnicode=yes&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baac3d3e572fba
    password: 32b37ff9251e59a
    validationQueryP: SELECT 1


#  Hibernate Configuration:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        connection:
          pool_size: 10

security:
  ignored: none